import { NextResponse } from "next/server";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { getResendClient } from "@/lib/email/resend";
import { getEmailConfig, getEmailHeaders } from "@/lib/email/email-config";
import { logEmail } from "@/lib/email/email-log.service";
import { buildPasswordResetEmail } from "@/lib/email/templates/password-reset";
import { verifyTurnstile } from "@/lib/auth/verify-turnstile";
import { rateLimit } from "@/lib/rate-limit";
import { logger } from "@/lib/logger";

export const dynamic = "force-dynamic";

const bodySchema = z.object({
  email: z.string().email().max(254),
  captchaToken: z.string().min(1).optional(),
  redirectPath: z.string().regex(/^\/[a-zA-Z0-9/_-]*$/).optional(),
});

// Recovery links generated by Supabase admin are valid for the project's
// configured email OTP expiry. Default is 3600s (60 min); we surface the
// conservative value in the email body so it never overstates expiry.
const LINK_EXPIRY_MINUTES = 60;

export async function POST(request: Request) {
  let parsed: z.infer<typeof bodySchema>;
  try {
    parsed = bodySchema.parse(await request.json());
  } catch {
    return NextResponse.json({ error: "Invalid request" }, { status: 400 });
  }

  const email = parsed.email.trim().toLowerCase();
  const redirectPath = parsed.redirectPath ?? "/reset-password";

  const ip =
    request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ||
    request.headers.get("x-real-ip") ||
    "unknown";

  // Per-email AND per-IP throttling. The per-IP key prevents a single bad
  // actor from spraying many emails; per-email caps the noise to a single
  // mailbox even if the attacker rotates IPs.
  const ipLimit = rateLimit(`forgot-password:ip:${ip}`, 10, 60_000);
  if (!ipLimit.allowed) {
    return NextResponse.json({ error: "Too many requests" }, { status: 429 });
  }
  const emailLimit = rateLimit(`forgot-password:email:${email}`, 3, 5 * 60_000);
  if (!emailLimit.allowed) {
    // Still return 200 so we don't leak whether the email exists.
    return NextResponse.json({ success: true });
  }

  const captcha = await verifyTurnstile(parsed.captchaToken, ip);
  if (!captcha.ok) {
    return NextResponse.json(
      { error: captcha.error ?? "Captcha verification failed" },
      { status: 400 },
    );
  }

  const appUrl =
    process.env.APP_URL ||
    process.env.NEXT_PUBLIC_SITE_URL ||
    "https://my.eckcm.com";
  const redirectTo = `${appUrl}/callback?next=${encodeURIComponent(redirectPath)}`;

  const admin = createAdminClient();

  const { data, error } = await admin.auth.admin.generateLink({
    type: "recovery",
    email,
    options: { redirectTo },
  });

  // Don't leak whether the email is registered. Silently succeed on
  // "user not found" / any other generateLink error; only log it.
  if (error || !data?.properties?.action_link) {
    if (error && error.status !== 404) {
      logger.error("[forgot-password] generateLink failed", {
        email,
        error: error.message,
        status: error.status,
      });
    }
    return NextResponse.json({ success: true });
  }

  const actionLink = data.properties.action_link;
  const { html, text } = buildPasswordResetEmail({
    resetUrl: actionLink,
    expiresInMinutes: LINK_EXPIRY_MINUTES,
  });

  try {
    const [resend, emailConfig] = await Promise.all([
      getResendClient(),
      getEmailConfig(),
    ]);

    const { data: sendResult, error: sendError } = await resend.emails.send({
      from: emailConfig.from,
      to: email,
      ...(emailConfig.replyTo ? { replyTo: emailConfig.replyTo } : {}),
      subject: "Reset your ECKCM password",
      html,
      text,
      headers: getEmailHeaders(),
    });

    if (sendError) {
      logger.error("[forgot-password] Resend send failed", {
        email,
        error: sendError.message,
      });
      await logEmail({
        toEmail: email,
        fromEmail: emailConfig.from,
        subject: "Reset your ECKCM password",
        template: "password-reset",
        status: "failed",
        errorMessage: sendError.message,
      });
    } else {
      await logEmail({
        toEmail: email,
        fromEmail: emailConfig.from,
        subject: "Reset your ECKCM password",
        template: "password-reset",
        status: "sent",
        resendId: sendResult?.id ?? null,
      });
    }
  } catch (err) {
    logger.error("[forgot-password] Unexpected send error", {
      email,
      error: String(err),
    });
  }

  return NextResponse.json({ success: true });
}
