// This file will be auto-generated by Supabase CLI: supabase gen types typescript
// For now, we define the core types manually based on the Design document.

export type Gender = "MALE" | "FEMALE" | "NON_BINARY" | "PREFER_NOT_TO_SAY";

export type Grade =
  | "PRE_K"
  | "KINDERGARTEN"
  | "GRADE_1"
  | "GRADE_2"
  | "GRADE_3"
  | "GRADE_4"
  | "GRADE_5"
  | "GRADE_6"
  | "GRADE_7"
  | "GRADE_8"
  | "GRADE_9"
  | "GRADE_10"
  | "GRADE_11"
  | "GRADE_12";

export type RegistrationStatus =
  | "DRAFT"
  | "SUBMITTED"
  | "PAID"
  | "CANCELLED"
  | "REFUNDED";

export type ChurchRole = "MEMBER" | "DEACON" | "ELDER" | "MINISTER" | "PASTOR";
export type GroupRole = "REPRESENTATIVE" | "MEMBER";
export type MemberStatus = "ACTIVE" | "INACTIVE";
export type RoomAssignStatus = "PENDING" | "ASSIGNED";
export type PricingType = "FLAT" | "PER_NIGHT" | "PER_MEAL" | "RULED";
export type SelectionMode = "AUTO" | "USER_SELECT" | "ADMIN_ONLY";
export type MealType = "BREAKFAST" | "LUNCH" | "DINNER";
export type CheckinType = "MAIN" | "DINING" | "SESSION" | "CUSTOM";
export type CheckinSource = "SELF" | "KIOSK";
export type PaymentStatus =
  | "PENDING"
  | "SUCCEEDED"
  | "FAILED"
  | "REFUNDED"
  | "PARTIALLY_REFUNDED";
export type PaymentMethod =
  | "CARD"
  | "APPLE_PAY"
  | "GOOGLE_PAY"
  | "ACH"
  | "CHECK"
  | "ZELLE"
  | "MANUAL";
export type StaffRole =
  | "PARTICIPANT"
  | "SUPER_ADMIN"
  | "EVENT_ADMIN"
  | "ROOM_COORDINATOR"
  | "CHECKIN_STAFF"
  | "SESSION_CHECKIN_STAFF"
  | "DINING_CHECKIN_STAFF"
  | "KEY_DEPOSIT_STAFF"
  | "CUSTOM";
